sudo: required 
services: 
  -  docker
before_install:
  - docker build -t liran/docker-react -f Dockerfile.dev .
script: 
  - docker run liran/docker-react echo "hello world"
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket: "elasticbeanstalk-us-east-1-252150623009"
  bucket_path: "docker-react-test"
  on: 
    branch: master
  access_key_id: $aws_key
  secret_access_key: 
    secure: "$aws_secret"
